spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.org.springframework=WARN

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always